name = "ipfg"
main = "./shims/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false

[[r2_buckets]]
binding = "WASM_BUCKET"
bucket_name = "ipfg-wasm"
preview_bucket_name = "ipfg-wasm-preview"

[observability]
enabled = true
 
