# kiosk -> non-root user for service monitoring gui
# 
# requires:
#   * Xorg X11 display server
#
# configure system:
# setcap cap_sys_tty_config+ep /usr/lib/Xorg
# usermod -aG video,input,render kiosk

[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin kiosk --noclear %I $TERM
