FROM gcr.io/distroless/cc-debian12:debug-nonroot AS debug
FROM gcr.io/distroless/nodejs24-debian12:nonroot

# Copy BusyBox shell for debugging
COPY --from=debug /busybox/busybox /bin/busybox

ENTRYPOINT ["/bin/busybox"]
CMD ["sh"]